config/urls.py
from django.contrib import admin
from django.urls import  include, path
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView




urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("", include("users.urls")),
    # path('', RedirectView.as_view(url='/home/', permanent=True))
]

core/urls.py
from django.urls import path, include
from .views import PostsView, PostsDetailView, PostsDeleteView, PostsUpdateView, PostsCreateView

app_name = "posts"

urlpatterns = [
    path("posts/", PostsView.as_view(), name = "list"),
    path("post_detail/<int:id>/", PostsDetailView.as_view(), name= "detail"),
    path("post_delete/<int:id>/", PostsDeleteView.as_view(), name="delete"),
    path("post_update/<int:id>/", PostsUpdateView.as_view(), name="update"),
    path("post_create/", PostsCreateView.as_view(), name="create"),
    path("accounts/", include("users.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
    
] 

core/models.py
# Models.py
"""Models of database."""

from django.db import models
from django.conf import settings



class Db(models.Model):
    """Database class."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=False, 
        on_delete=models.SET_NULL, related_name="+")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_At = models.DateTimeField(auto_now=True)

    class Meta:
        """Meta class."""
        permissions =  (("posts", "users"),)
        abstract = True


class Post(Db):
    """Post class."""

    title = models.CharField(max_length=100, null=False, blank=False)
    content = models.TextField(null=False, blank=False)
    image = models.CharField(max_length=255, null=True, blank=True)

    # def save(self, commit):
    #     pass

    def __str__(self) -> str:
        """Print Title, User, Content."""
        return 'Title: %s |  User: %s | Content: %s' % (self.title, self.user, self.content)
        # return f"{self.title}"

class Like(Db):
    """Like class."""

    post = models.ForeignKey("Post", null=False, blank=False, on_delete=models.CASCADE)
    status = models.BooleanField(null=True, blank=True)

core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Post

User = get_user_model()

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]
  

core/views.py
from django.shortcuts import render
"""Views."""
#from django.views.generic import TemplateView
#from telnetlib import STATUS
#from urllib import request
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from django.urls import reverse_lazy

from django.contrib.auth.mixins import PermissionRequiredMixin

from .models import Post
from .forms import PostForm, User


# def posts(requests):
#     posts = Post.objects.all()
#     results = ", ".join([post.title for post in posts])
# 
#     # posts = "post 1 : King Artur"
#     return HttpResponse(f"<h1>{results}</h1>")


# class PostsView(TemplateView):
#     template_name = 'core/posts.html'   
# 
#     def get_context_data(self, **kwargs):
#         ctx = super().get_context_data(**kwargs)
#         ctx['posts'] = Post.objects.all()
#         return ctx


class PostsView(PermissionRequiredMixin, ListView):
    permission_required = 'core.posts'
    queryset = Post.objects.all()
    template_name = 'core/posts.html' 
    # p = Post.objects.first()
    # post_likes = p.like_set.all()
    
    # contex_object_name = "posts"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        posts = Post.objects.all()
        results = [
            (
            p,
            p.like_set.filter(status=True).count(),
            p.like_set.filter(status=False).count(),            
            )
            for p in posts
        ]
        ctx["results"] = results
        return ctx

class PostsDetailView(DetailView):
    queryset = Post.objects.all()
    template_name = 'core/post_ob.html'
    pk_url_kwarg = 'id'
    

class PostsDeleteView(DeleteView):
    queryset = Post.objects.all()
    template_name = 'core/post_delete.html'
    pk_url_kwarg = 'id'
    success_url = reverse_lazy("posts:list")

class PostsUpdateView(UpdateView):
    queryset = Post.objects.all()
    template_name = 'core/post_update.html'
    pk_url_kwarg = 'id'
    fields = ["title", "content"]
    success_url = reverse_lazy("posts:list")

    

class PostsCreateView(CreateView):
    queryset = Post.objects.all()
    template_name = 'core/post_create.html'
    #fields = ["created_at", "title", "content", "user"]
    success_url = reverse_lazy("posts:list")
    form_class = PostForm

    def form_valid(self, form):
        user = User.objects.first()
        form.instance.user = user
        return super().form_valid(form)

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    {% block css %}
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}" />
        {% endblock %}
    </head>
    <body>
    <div class="container">
        <div class="my_op">
        <img src={% static "/img/179341304.jpg" %} alt="flag" style="float:left;width:42px;height:32px;">       
        <img src={% static "/img/european-union-155207_960_720.png" %} alt="flag" style="float:left;width:42px;height:32px;margin-left:0px;">     
        <img src={% static "/img/union-jack-26119_960_720.webp" %} alt="flag" style="float:left;width:42px;height:32px;margin: left 0px;">
        <img src={% static "/img/america-flag-2043285__340.webp" %} alt="flag" style="float:left;width:42px;height:32px;margin: left 0px;">
         
        <!-- <div class="tur2">
            <img src={% static "/img/3ukr.png" %} alt="flag" style="float:left;width:32px;height:32px;">       
            <img src={% static "/img/CE.png" %} alt="flag" style="float:left;width:42px;height:25px;margin-left:0px;">     
            <img src={% static "/img/UKCA.webp" %} alt="flag" style="float:left;width:42px;height:32px;margin: left 0px;">
            <img src={% static "/img/FCC_New_Logo.svg.png" %} alt="flag" style="float:left;width:42px;height:32px;margin: left 0px;">
            </div> -->
        
            </div>
        <div class="my_op_2"><h3 style="margin-left:15px;" >Django Auth Model</h3></div> 
    </div> 


    <header >
        
            
            
            <hr style="height:4px;  background-color:blue;margin: 0;margin-top:5px;">
            <hr style="height:4px;background-color:rgb(246, 246, 11);margin: 0;">
            
            <div class="my_op_1">
              <h6><a href="/admin/">admin</a> | <a href="/posts/">posts</a> | <a href="/users/">users</a></h6>
            </div>

            <div class="container">
                {% if not user.is_authenticated %}
                   <div class="my_op_1"> <a href="{% url 'login' %}">LogIn</a> | <a href="{% url 'signup' %}">SignUp</a>
                {% else %}
                   <div class="my_op_1"> Hi, {{ user.username }} | <a href="{% url 'logout' %}">Logout</a></div>
                {% endif %}
            </div>            
        </header>

        <main>
            <div >
                <div >
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </main>
        <div class="navbar-fixed-bottom">
            <div class="container">
                    <footer> all rights reserved &#169</footer>
            </div>
        </div>
        {% block js %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    {% endblock %}
        
    </body>
    
</html>

templates/core/post_create.html
{% extends 'core/base.html' %} 

{% block content %}
    <title>Update Page</title>
    <h4><a>Create A New Post:</a></h4>
           
    <form method="post" action="">
        {% csrf_token %}
        <div> {{ form.title.label }}: {{ form.title }}</div>
        <div> {{ form.content.label }}: {{ form.content }}</div>
        <button type="submit">Confirm</button>
        </form>
    
{% endblock %}

templates/core/post_delete.html
{% extends 'core/base.html' %} 

{% block content %}
    <title>Delete Page</title>
    <h4><a href="/admin/core/post/">Delete This Post:</a></h4>
  
        <article class="post">
            <div>{{ object }} </div>
        </article> 
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm</button>
    </form>
    
{% endblock %}

templates/core/post_ob.html
{% extends 'core/base.html' %} 

{% block content %}
    <title>Posts ob</title>
    <h4><a href="/admin/core/post/">Posts Detailed:</a></h4>
  
        <article class="post">
            <div> {{ object }} </div>
        </article>  
        

    <a href="{% url 'posts:delete' object.id %}">Delete post</a>
    <a href="{% url 'posts:update' object.id %}">Update post</a>
{% endblock %}

templates/core/post_update.html
{% extends 'core/base.html' %} 

{% block content %}
    <title>Update Page</title>
    <h4><a href="/admin/core/post/">Update This Post:</a></h4>
  
        <article class="post">
            <div>{{ object }} </div>
        </article> 
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Confirm</button>
    </form>
    
{% endblock %}

templates/core/posts.html
{% extends 'core/base.html' %} 
{% load static %}
{% block title %}Posts{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}" />

   
   <ol>
    <dev> 
   <table class="table_head" style="margin: auto;">
    <tr>
        <th colspan="7" class="border"><h4><a href="/admin/core/post/">Posts:</a></h4> </th>                    
    </tr>
        <tr >
            <td class="border">Posts</td>
            <td class="border">Likes</td>
            <td class="border">dislikes</td>
           </tr>
        {% for post, likes, dislikes in results %}
        <tr>
            <td class="border">{{ post.title }}</td>
            <td class="border">{{likes }}</td>
            <td class="border">{{ dislikes }}</td>
        </tr>
        {% endfor %}


          </table>
        </dev>
    </ol>
    <div class="my_op_head_1">
    <button class="button_create"  onClick='location.href="{% url "posts:create" %}"'>Create a new post</button>
    <!-- <h4 class="my_op_1"><a href="{% url 'posts:create' %}" target="_blank" >Create a new post</a></h4> -->
    </div>
{% endblock %}